In [27]:
import h5py 
import numpy as np
import pennylane as qml
from train import bgs 

In [28]:
[dataset] = qml.data.load("other", name="bars-and-stripes") 
inputs = dataset.train['4']['inputs'] # images de pixels 4x4 
    
# Dimensions des inputs: (N, D) 
inputs_np = np.array(inputs)
nb_samples = inputs_np.shape[0] # N ---> samples
nb_pixels  = inputs_np.shape[1] # D ---> features

Nv = 16
Nh = 3

In [29]:
with h5py.File("rbm_parameters.h5", "r") as f:
    print(f.keys()) 

    w     = np.array(f['weight_matrix'])
    eta   = np.array(f['eta_vector'])    
    theta = np.array(f['theta_vector'])

    print(w)
    print(eta)
    print(theta)

<KeysViewHDF5 ['weight_matrix', 'eta_vector', 'theta_vector']>
[[-0.06785619 -0.06827611 -0.06826973]
 [-0.06647932 -0.06646492 -0.06748908]
 [-0.06910775 -0.06916351 -0.07045635]
 [-0.06444804 -0.06446854 -0.06606468]
 [-0.0669508  -0.06643666 -0.06710178]
 [-0.06149781 -0.06316798 -0.06260539]
 [-0.06761507 -0.06701647 -0.06742024]
 [-0.06080567 -0.06169065 -0.0621395 ]
 [-0.06270951 -0.06195288 -0.0621403 ]
 [-0.06275034 -0.0605812  -0.06198147]
 [-0.06071896 -0.06059491 -0.06139799]
 [-0.05962676 -0.0585182  -0.06141097]
 [-0.06748023 -0.0669831  -0.06731738]
 [-0.06373845 -0.06318963 -0.06385668]
 [-0.06427566 -0.06447386 -0.06342409]
 [-0.06413063 -0.06191573 -0.06573268]]
[-0.00088246 -0.00013006 -0.00148428]
[-0.12201989 -0.11834607 -0.12491527 -0.11570442 -0.11996059 -0.11077194
 -0.1193373  -0.10943482 -0.11064281 -0.10943587 -0.10732551 -0.10430298
 -0.11977924 -0.11198185 -0.11459081 -0.11269785]


In [31]:
h, v = bgs(w, eta, theta, Nv, Nh, 10)

TypeError: bgs() takes from 3 to 4 positional arguments but 6 were given